name: Deploy staging

on:
  push:
    branches:
      - develop
      - 'release/**'

jobs:
  deploy_staging_debug:
    name: Deploy staging debug
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Java environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Decrypt secret
        run: ./.github/workflows/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Bump version code
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }}

      - name: Build staging debug APK
        run: ./gradlew assembleStagingDebug

      - name: Upload staging debug APK to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_STAGING }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: developer
          releaseNotes: Staging debug build
          file: app/build/outputs/apk/staging/debug/app-staging-debug.apk
